# Generated by Django 3.2.13 on 2022-07-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_exam_score', models.BooleanField(default=True)),
                ('require_test_score', models.BooleanField(default=True)),
                ('require_performance_score', models.BooleanField(default=True)),
                ('require_listening_score', models.BooleanField(default=False)),
                ('require_speaking_score', models.BooleanField(default=False)),
                ('exam_score', models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4, null=True)),
                ('test_score', models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4, null=True)),
                ('performance_score', models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4, null=True)),
                ('listening_score', models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4, null=True)),
                ('speaking_score', models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.subject')),
            ],
        ),
    ]
