# Generated by Django 3.2.13 on 2022-07-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0002_auto_20220714_1631'),
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
    ]
