# Generated by Django 3.2.13 on 2022-07-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_merge_0002_auto_20220714_1631_0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='require_exam_score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='require_listening_score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='require_performance_score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='require_speaking_score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='require_test_score',
        ),
    ]
