# Generated by Django 3.2.13 on 2022-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0007_subject_is_complex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='exam_score',
            field=models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('45%', '45%'), ('50%', '50%'), ('75%', '75%'), ('90%', '90%')], max_length=4),
        ),
    ]
