# Generated by Django 3.2.13 on 2022-08-14 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0008_alter_mark_exam_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='is_complex',
        ),
        migrations.AddField(
            model_name='academicterm',
            name='weightage',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
