# Generated by Django 3.2.13 on 2022-08-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0009_auto_20220814_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], max_length=4, null=True),
        ),
    ]
