# Generated by Django 3.2.13 on 2022-08-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0010_alter_academicterm_weightage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicterm',
            name='weightage',
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(blank=True, choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Final Result', 'Final Result')], max_length=20, null=True),
        ),
    ]
