# Generated by Django 3.2.13 on 2022-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0011_auto_20220818_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='first_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='second_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='third_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], max_length=4, null=True),
        ),
    ]
