# Generated by Django 3.2.13 on 2022-08-18 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0012_auto_20220818_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term'), ('Final Result', 'Final Result')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
