# Generated by Django 3.2.13 on 2022-08-18 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0013_alter_academicterm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='first_weightage',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='second_weightage',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='third_weightage',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('60%', '60%')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
