# Generated by Django 3.2.13 on 2022-09-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corecode', '0016_markauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='first_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='second_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='third_weightage',
            field=models.CharField(blank=True, choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam_score',
            field=models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('88%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], max_length=4),
        ),
        migrations.AlterField(
            model_name='mark',
            name='listening_score',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('88%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='performance_score',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('88%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='speaking_score',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('88%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='test_score',
            field=models.CharField(blank=True, choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('88%', '80%'), ('85%', '85%'), ('90%', '90%'), ('95%', '95%'), ('100%', '100%')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='markauditlog',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.mark'),
        ),
        migrations.AlterField(
            model_name='markauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
